### ISSUE TITLE
App crashes on iOS

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [greenbits/datadog_flutter#109]
Hello, after flutter update to 3.0.5 app started to crash on iOS using this plugin version 2.0.0

```
[DATADOG SDK] 🐶 → 13:43:55.060 [ERROR] 'dd.trace_id' is a reserved attribute name. This attribute will be ignored.
[DATADOG SDK] 🐶 → 13:43:55.060 [ERROR] 'dd.span_id' is a reserved attribute name. This attribute will be ignored.
flutter: AuthenticationStatus.authenticated
2
datadog_flutter/SwiftDatadogFlutterPlugin.swift:267: Fatal error: Unexpectedly found nil while unwrapping an Optional value
* thread #1, queue = 'com.apple.main-thread', stop reason = Fatal error: Unexpectedly found nil while unwrapping an Optional value
    frame #0: 0x00000001e4a4a458 libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`_swift_runtime_on_report:
->  0x1e4a4a458 <+0>: ret
libswiftCore.dylib`_swift_reportToDebugger:
    0x1e4a4a45c <+0>: b      0x1e4a4a458               ; _swift_runtime_on_report
libswiftCore.dylib`_swift_shouldReportFatalErrorsToDebugger:
    0x1e4a4a460 <+0>: adrp   x8, 335240
    0x1e4a4a464 <+4>: ldrb   w0, [x8, #0x45c]
Target 0: (Runner) stopped.
Lost connection to device.
```

Also for some reasons i see another error in here ```dd.trace_id' is a reserved attribute name```

**Comment by mateusfccp** [comment]
Yeah, we are also having it when upgrading from 3.0 to 3.3. Also, the official Datadog flutter simply does not work.

**Comment by tshedor** [comment]
Sorry - this plugin is deprecated. Please open any issues with the official plugin on their repo at https://github.com/DataDog/dd-sdk-flutter
